"""Pydantic response schemas for AI-generated content.

Validates and structures AI outputs for CVE alerts, chain narratives, 
and phishing simulations.
"""

from typing import Optional

from pydantic import BaseModel, Field, validator


class CVESynthesisResponse(BaseModel):
    """Plain-English CVE alert generated by AI."""

    alert: str = Field(
        ...,
        description="Plain-English explanation of CVE and impact",
        max_length=1000,
    )
    """Non-technical explanation of the vulnerability."""

    remediation: str = Field(
        ...,
        description="Patch/mitigation steps",
        max_length=500,
    )
    """Specific actions to take to remediate."""

    urgency: str = Field(
        ...,
        description="Priority level",
        regex="^(Critical|High|Medium|Low)$",
    )
    """How urgent this CVE is for action (Critical/High/Medium/Low)."""

    class Config:
        """Pydantic config."""

        schema_extra = {
            "example": {
                "alert": "This vulnerability in Apache allows remote attackers to execute code on your server. Your organization is affected because you use Apache.",
                "remediation": "Update Apache to version 2.4.53 or later. Restart the Apache service.",
                "urgency": "Critical",
            }
        }


class ChainAnalysisResponse(BaseModel):
    """Chain analysis explaining multi-hop vulnerability."""

    narrative: str = Field(
        ...,
        description="Plain-English explanation of how CVEs combine",
        max_length=1500,
    )
    """Non-technical narrative of how the chain works."""

    attack_steps: list[str] = Field(
        ...,
        description="Numbered steps in the attack",
        max_items=10,
    )
    """Ordered steps attacker would take."""

    impact: str = Field(
        ...,
        description="Expected outcome if exploited",
        max_length=500,
    )
    """What damage could result from successful exploitation."""

    class Config:
        """Pydantic config."""

        schema_extra = {
            "example": {
                "narrative": "An attacker could exploit a web vulnerability to gain initial access, then use a privilege escalation flaw to gain admin rights.",
                "attack_steps": [
                    "Exploit web vulnerability to access server",
                    "Escalate privileges using kernel flaw",
                    "Install backdoor for persistent access",
                ],
                "impact": "Complete system compromise and data exfiltration",
            }
        }


class PhishingSimulationResponse(BaseModel):
    """Generated phishing email for security awareness simulation."""

    subject: str = Field(
        ...,
        description="Email subject line",
        max_length=200,
    )
    """Phishing email subject."""

    body: str = Field(
        ...,
        description="Email body content",
        max_length=2000,
    )
    """Phishing email message."""

    sender_identity: str = Field(
        ...,
        description="What/who the email claims to be from",
        max_length=200,
    )
    """Claimed sender (e.g., 'IT Security Team', 'CEO', 'HR')."""

    class Config:
        """Pydantic config."""

        schema_extra = {
            "example": {
                "subject": "[URGENT] Security Update - Action Required",
                "body": "Your account has been flagged for suspicious activity. Please verify your credentials...",
                "sender_identity": "IT Security Team",
            }
        }


class StackVulnerabilityAlert(BaseModel):
    """Complete alert for a single vulnerability in a stack."""

    cve_id: str = Field(..., description="CVE identifier")
    """The CVE ID."""

    priority_label: str = Field(
        ...,
        description="Priority level",
        regex="^(CRITICAL|HIGH|MEDIUM|LOW)$",
    )
    """SentryIQ priority label."""

    priority_score: float = Field(..., ge=0, le=100, description="Numeric score 0-100")
    """Composite priority score."""

    plain_english_alert: str = Field(..., description="AI-generated plain-English alert")
    """Non-technical alert text."""

    remediation_steps: str = Field(..., description="AI-generated remediation steps")
    """Specific fix/patch instructions."""

    is_part_of_chain: bool = Field(default=False, description="Is this part of a detected chain")
    """Whether this CVE is part of a detected vulnerability chain."""

    class Config:
        """Pydantic config."""

        schema_extra = {
            "example": {
                "cve_id": "CVE-2024-12345",
                "priority_label": "CRITICAL",
                "priority_score": 89.5,
                "plain_english_alert": "An Apache vulnerability allows attackers to run code on your server...",
                "remediation_steps": "Update Apache to 2.4.53 and restart.",
                "is_part_of_chain": False,
            }
        }


class VulnerabilityChainAlert(BaseModel):
    """Alert for a detected vulnerability chain."""

    chain_id: str = Field(..., description="Unique chain identifier")
    """Chain UUID."""

    cve_ids: list[str] = Field(..., description="CVE IDs in chain")
    """List of CVEs forming the chain."""

    chain_score: float = Field(..., ge=0, le=100, description="Chain risk score")
    """Composite chain score."""

    attack_outcome: str = Field(
        ...,
        description="Expected outcome",
        regex="^(RCE|PRIVESC|EXFIL|AUTH_BYPASS|CHAIN_ATTACK)$",
    )
    """What the attacker gains if successful."""

    chain_narrative: str = Field(..., description="AI-generated chain explanation")
    """Non-technical explanation of the chain."""

    class Config:
        """Pydantic config."""

        schema_extra = {
            "example": {
                "chain_id": "chain-abc123",
                "cve_ids": ["CVE-2024-111", "CVE-2024-222"],
                "chain_score": 92.0,
                "attack_outcome": "RCE",
                "chain_narrative": "An attacker could exploit XSS to inject code, then escalate to RCE...",
            }
        }
